Help messages.

diff --git a/frankentree b/frankentree
--- a/frankentree
+++ b/frankentree
@@ -96,22 +96,28 @@ function fork_repo {
 # =============================================================
 # COMMANDS
 
+function display_push_upstream_help {
+    echo "Usage:"
+    echo "    repo-manage push-upstream -h              display this help message."
+    echo "    repo-manage push-upstream FOLDER_NAME     pushes changes to upstream repo."
+}
+
 function command_push_upstream {
 
     while getopts ":h" opt; do
         case ${opt} in
             h )
-                echo "Usage:"
-                echo "    repo-manage push-upstream -h              display this help message."
-                echo "    repo-manage push-upstream ROLE_NAME       pushes changes to upstream role repo."
+                display_push_upstream_help
                 exit 0
                 ;;
             \? )
                 echo "Invalid Option: -$OPTARG" 1>&2
+                display_push_upstream_help
                 exit 1
                 ;;
             : )
                 echo "Invalid Option: -$OPTARG requires an argument" 1>&2
+                display_push_upstream_help
                 exit 1
                 ;;
         esac
@@ -121,10 +127,13 @@ function command_push_upstream {
 
     if [[ "$#" -ne 1 ]]; then
         echo ""
-        echo "Illegal number of arguments: exactly one ROLE_NAME allowed."
+        echo "Illegal number of arguments: exactly one FOLDER_NAME allowed."
         echo ""
+        display_push_upstream_help
         exit 1
     fi
+
+    check_git_status
 
     # reading path to role
     while read -r line; do
@@ -132,7 +141,7 @@ function command_push_upstream {
             continue
         fi
         declare "$line";
-    done <".role_repos"
+    done <".folder_repos"
 
     clean_string role_key "$1"
     role_path=${!role_key}
@@ -142,36 +151,44 @@ function command_push_upstream {
 
 }
 
+function display_pull_upstream_help {
+    echo "Usage:"
+    echo "    repo-manage pull-upstream -h              display this help message."
+    echo "    repo-manage pull-upstream FOLDER_NAME     pulls changes from upstream repo."
+}
+
 function command_pull_upstream {
 
    while getopts ":h" opt; do
      case ${opt} in
      h )
-      echo "Usage:"
-      echo "    repo-manage pull-upstream -h              display this help message."
-      echo "    repo-manage pull-upstream ROLE_NAME       pulls changes from upstream repo."
+         display_pull_upstream_help
       exit 0
       ;;
      \? )
        echo "Invalid Option: -$OPTARG" 1>&2
+       display_pull_upstream_help
        exit 1
        ;;
      : )
        echo "Invalid Option: -$OPTARG requires an argument" 1>&2
+       display_pull_upstream_help
        exit 1
        ;;
      esac
    done
 
-
    shift $((OPTIND -1))
 
    if [[ "$#" -ne 1 ]]; then
       echo ""
-      echo "Illegal number of arguments: exactly one ROLE_NAME allowed."
+      echo "Illegal number of arguments: exactly one FOLDER_NAME allowed."
       echo ""
+      display_pull_upstream_help
       exit 1
    fi
+
+   check_git_status
 
    # reading path to role
    while read -r line; do
@@ -179,7 +196,7 @@ function command_pull_upstream {
            continue
        fi
        declare "$line";
-   done <".role_repos"
+   done <".folder_repos"
 
    clean_string role_key "$1"
    role_path=${!role_key}
@@ -193,14 +210,18 @@ function command_pull_upstream {
 
 }
 
+function display_add_help {
+    echo "Usage:"
+    echo "    repo-manage add -h                                display this help message."
+    echo "    repo-manage add [-f] -p LOCAL_PATH REPO_URL       adds a remote repo."
+}
+
 function command_add {
    fork=false
    while getopts ":hfp:" opt; do
      case ${opt} in
      h )
-      echo "Usage:"
-      echo "    repo-manage add -h                                display this help message."
-      echo "    repo-manage add [-f] -p LOCAL_PATH REPO_URL       adds a remote repo."
+      display_add_help
       exit 0
       ;;
      f )
@@ -211,10 +232,12 @@ function command_add {
        ;;
      \? )
        echo "Invalid Option: -$OPTARG" 1>&2
+       display_add_help
        exit 1
        ;;
      : )
        echo "Invalid Option: -$OPTARG requires an argument" 1>&2
+       display_add_help
        exit 1
        ;;
      esac
@@ -226,6 +249,7 @@ function command_add {
       echo ""
       echo "No local path provided, please use '-p' option"
       echo ""
+      display_add_help
       exit 1
    else
       if [[ -e ${local_path} ]]; then
@@ -242,6 +266,8 @@ function command_add {
       echo ""
       exit 1
    fi
+
+   check_git_status
 
    repo_url="$1"
    echo "$repo_url"
@@ -262,13 +288,25 @@ function command_add {
    git subtree add --prefix ${local_path} ${upstream_alias} master --squash || error_exit "Could not add remote tree '${repo_url}' to: ${local_path}"
 
    echo "Added repositury '${repo_url}' (using alias '${upstream_alias}' at path: ${local_path}"
-   echo "${role_name}=${local_path}" >> .role_repos
+   echo "${role_name}=${local_path}" >> .folder_repos
+   echo "${role_name}=${repo_url}" >> .remote_repos
 
-   git add .role_repos
-   git commit -m "Added remote role repo '${repo_url}' (alias: ${upstream_alias})to path: ${local_path}"
+   git add .folder_repos
+   git add .remote_repos
+   git commit -m "Added remote folder repo '${repo_url}' (alias: ${upstream_alias})to path: ${local_path}"
 }
 
+function display_help {
+    echo "Usage:"
+    echo "    frankentree -h                      Display this help message."
+    echo "    frankentree add                     Adds a git subtree."
+    echo "    frankentree pull-upstream           (git) pulls all subtrees."
+    echo "    frankentree push-upstream           (git) pushes all subtrees."
+}
 
+function check_git_status {
+    git diff-index --quiet HEAD -- || error_exit "local git repository has modifications, not doing anything..."
+}
 
 # =============================================================
 # VARS
@@ -278,10 +316,29 @@ PROGNAME="repo-manage"
 # =============================================================
 # ARG PARSING
 
+while getopts ":h" opt; do
+    case ${opt} in
+        h )
+            display_help
+            exit 0
+            ;;
+        \? )
+            echo "Invalid Option: -$OPTARG" 1>&2
+            display_help
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND -1))
+
+if [ -z "$1" ]
+then
+    display_help
+    exit 0
+fi
+
 subcommand=$1
 shift
-
-git diff-index --quiet HEAD -- || error_exit "local git repository has modifications, not doing anything..."
 
 case "$subcommand" in
   add)
